version: '3.8'

services:
  kavita:
    image: kizaing/kavita:latest
    container_name: kavita
    ports:
      - "5555:5000"
    volumes:
      - /Users/weidian/Desktop/books:/books
      - ./kavita-config:/kavita/config
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
